### ISSUE TITLE
会循环引用

### ISSUE THREAD

**Issue by YYHNobug** [zmubai/BNM3u8Cache#1]
BNM3U8Manager用单例类，block回调进度，会循环引用吧，我在二级界面写了个下载的TableView，从第二级界面返回到一级界面后，在次进入二级进度无法展示

**Comment by zmubai** [comment]
进入二级界面，重新调用了这个方法吗？
- (void)downloadVideoWithConfig:(BNM3U8DownloadConfig *)config progressBlock:(BNM3U8DownloadProgressBlock)progressBlock resultBlock:(BNM3U8DownloadResultBlock)resultBlock;

如果是同一个url的话，内部回去判断任务是否存在。
- (void)downloadVideoWithConfig:(BNM3U8DownloadConfig *)config progressBlock:(BNM3U8DownloadProgressBlock)progressBlock resultBlock:(BNM3U8DownloadResultBlock)resultBlock{
    NSParameterAssert(config.url);
    LOCK(_operationSemaphore);
    if([_downloadOperationsMap.allKeys containsObject:config.url]){
        NSLog(@"任务已经存在！");
        UNLOCK(_operationSemaphore);
        return;
    }
......

**Comment by YYHNobug** [comment]
嗯，下载逻辑是没问题的，进度block里的UIView会循环引用，显示不了下载进度，你把你的Demo放在二级界面进行下载，就会发现问题了

**Comment by YYHNobug** [comment]
还有个问题，这个demo下载到本地用IJK播放不了，用m3u8DownloadSimpleDemo这个下载后IJK是可以播的，什么情况？

**Comment by zmubai** [comment]
需要本地服务才能开启

**Comment by zmubai** [comment]
需要开启本地http服务才能播放。

**Comment by YYHNobug** [comment]
是的，本地有开启HTTP服务，用m3u8DownloadSimpleDemo这个Demo  AVPlayer和IJK都是可以播的，用M3U8DemoByOperation这个demo，AVPlayer可以播，但用IJK不能播

**Comment by zmubai** [comment]
已修复：
主要问题：
url 拼接出现了错误，导致播放错误。stringByAppendingPathComponent 会导致http:// 变成 http:/  。

**Comment by YYHNobug** [comment]
嗯，可以了，那个循环引用导致进度无法展示的有解决方案没，感觉这个问题很经典

**Comment by zmubai** [comment]
看了下这个问题，不是循环引用导致的。因为每个m3u8下载任务都是全局的，他的进度回调，结果回调都不能被更新，所以需要用类似一个单例这样全局的容器来持有保持回调。另外，如果任务存在，那么也不会重新创建，任务的全部回调会走，只不过是之前设定的回调。如果要实现二级界面这样的，可以先把任务cannel了，再发起。

**Comment by zmubai** [comment]
调一下 [[BNM3U8Manager shareInstance]cancelAll]; 再发起。

**Comment by zmubai** [comment]
这个issue先关了，有问题再开一个哈
